# $LOAD_PATH handling not need if the standalone_migrations_new
# gem is installed
lib = File.expand_path("../../lib", __FILE__)
$:.unshift lib unless $:.include?(lib)

require "standalone_migrations_new"
StandaloneMigrationsNew::Tasks.load_tasks

# and that's it!
