#!/usr/bin/env ruby
require 'rubygems'
require 'active_record'
require 'optparse'

if ARGV[0] =~ /VERSION=\d+/
	version = ARGV[0].split('=')[1].to_i
else
	version = nil
end

logger = Logger.new $stderr
logger.level = Logger::INFO
ActiveRecord::Base.logger = logger
ActiveRecord::Base.colorize_logging = false
ActiveRecord::Base.establish_connection(YAML::load(File.open('config/database.yml')))

puts "Current database version: " + ActiveRecord::Migrator.current_version.to_s
ActiveRecord::Migrator.migrate("./migrations", version)
puts "New database version: " + ActiveRecord::Migrator.current_version.to_s
