#!/usr/bin/env ruby

if ARGV.empty?
    puts "Error: must provide name of migration to generate."
    puts "For example: ./new_migration us_131_add_field_to_form"
    exit 1
end

file_name = "migrations/#{Time.now.utc.strftime('%Y%m%d%H%M%S')}_#{ARGV[0]}.rb"
class_name = ARGV[0].split('_').map { |s| s.capitalize }.join

file_contents = <<eof
class #{class_name} < ActiveRecord::Migration
    def self.up
    end

    def self.down
        raise ActiveRecord::IrreversibleMigration
    end
end
eof

File.open(file_name, 'w') { |f| f.write file_contents }

puts "Created migration #{file_name}"
