# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: standalone_migrations_new 7.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "standalone_migrations_new".freeze
  s.version = "7.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Serhii Hiba".freeze, "Serhii Hiba".freeze]
  s.date = "2022-05-02"
  s.email = "enotikalt@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "example/.gitignore",
    "example/Rakefile",
    "example/db/config.yml",
    "example/db/migrate/20120930053225_create_table_awesome_migration.rb",
    "lib/standalone_migrations_new.rb",
    "lib/standalone_migrations_new/callbacks.rb",
    "lib/standalone_migrations_new/configurator.rb",
    "lib/standalone_migrations_new/generator.rb",
    "lib/standalone_migrations_new/minimal_railtie_config.rb",
    "lib/standalone_migrations_new/tasks.rb",
    "lib/standalone_migrations_new/tasks/connection.rake",
    "lib/standalone_migrations_new/tasks/db/new_migration.rake",
    "lib/standalone_migrations_new/tasks/environment.rake",
    "lib/tasks/standalone_migrations_new.rb",
    "spec/spec_helper.rb",
    "spec/standalone_migrations_new/callbacks_spec.rb",
    "spec/standalone_migrations_new/configurator_spec.rb",
    "spec/standalone_migrations_new_spec.rb",
    "standalone_migrations_new.gemspec",
    "vendor/migration_helpers/MIT-LICENSE",
    "vendor/migration_helpers/README.markdown",
    "vendor/migration_helpers/init.rb",
    "vendor/migration_helpers/lib/migration_helper.rb"
  ]
  s.homepage = "http://github.com/thuss/standalone-migrations".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.4".freeze
  s.summary = "A thin wrapper to use Rails Migrations in non Rails projects".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end
end

